puzzles: update SCR_URI to use main branch
The upstream repository has renamed from master branch to main. This
causes fetch errors like:

ERROR: puzzles-2_0.0+gitAUTOINC+79a5378b5a-r0 do_fetch: Fetcher failure: Unable to find revision 79a5378b5adc46ee33ba34d55738f916fb8adfc9 in branch master even from upstream
ERROR: puzzles-2_0.0+gitAUTOINC+79a5378b5a-r0 do_fetch: Fetcher failure for URL: 'git://git.tartarus.org/simon/puzzles.git'. Unable to fetch URL from any source.

Fix it by adding a bbappend to add the branch=main parameter in SRC_URI.

See:
yoctoproject/poky@ac746716fc puzzles: Upstream changed to main branch for development
yoctoproject/poky@07be05c698 meta: Add explict branch to git SRC_URIs, handle github url changes

Signed-off-by: Alexander Herfurtner <alexander.h@variscite.com>