meta-freescale: imx-alsa-plugins: move source from codeaurora to github
As of March 31, 2023, all codeaurora.org repositories have been
migrated to other platforms and the project has been shut down.
For more information, please visit: https://bye.codeaurora.org/.

Fix the following during bitbake fsl-image-gui:

ERROR:
    imx-alsa-plugins-1.0.26-r0 do_unpack: Unpack failure for URL:
    'git://source.codeaurora.org/external/imx/imx-alsa-plugins.git;
     protocol=https;branch=nxp/master'.
    No up to date source found.
ERROR: imx-alsa-plugins-1.0.26-r0 do_unpack: Function failed: base_do_unpack.

Signed-off-by: Alifer Moraes <alifer.m@variscite.com>