wxwidgets_3.2.0.bbappend: fix conflict error on DISTRO=fsl-framebuffer (tweaked the commit for dunfell because of the differece between kirkstone and dunfell)
Parsing recipes...ERROR: .../meta-variscite-fslc/recipes-extended/wxwidgets/wxwidgets_3.2.0.bb: wxwidgets: PACKAGECONFIG[gstreamer] Conflict package config 'no_gui' set in PACKAGECONFIG.
ERROR: Failed to parse recipe: .../meta-variscite-fslc/recipes-extended/wxwidgets/wxwidgets_3.2.0.bb

Signed-off-by: Masaru Tsuchiyama <m.tmatma@gmail.com>